### ISSUE TITLE
Cron Tasks Hanging

### ISSUE THREAD

**Issue by mneumegen** [javan/whenever#265]
I have a cron task the runs once a minute. Usually it will work fine but once a day one of the runs get's into a weird state where it just hangs forever and uses 100% of the CPU. I ran strace on the process and it's calling sched_yield() over and over again. After a bit of research I found someone had a similar problem with another Gem and the answer was turning new relic off with an environment variable.

I'm using the runner syntax in Whenever and deploy using Capistrano. How do I set an environment variable when the cron is run of NEWRELIC_ENABLE=false

**Comment by StaverDmitry** [comment]
This is super old but saved me some time pinpointing the troublemaker.
If anyone comes across this issue: the problem seems to be that new relic in its separate thread probably fails to initialise if the rake task is short enough and retries infinitely while the task waits for it to finish creating an endless loop.
