### ISSUE TITLE
How to test in development environment?

### ISSUE THREAD

**Issue by fabianoalmeida** [javan/whenever#351]
I have a cron on my app and I'm trying to test it, but it's not running. My config:

``` ruby
# Gemfile
gem 'whenever', require: false
```

My schedule

``` ruby
# config/schedule.rb
set :output, { error: 'error.log', standard: 'cron.log' }

every 2.minutes do
  runner "Cron.get_categories"
end
```

And my cron

``` ruby
# lib/cron.rb
class Cron
  def self.get_categories
    p "Testing..."
  end
end
```

And the text is not printing on my console. Is there any other configuration to do?

Thanks in advance!

**Comment by lgs** [comment]
@fabianoalmeida  in your local crontab, instead of 

`* * * * * /bin/bash -l -c 'cd /Users/app && script/rails runner -e development '\''Cron.get_categories'\'' >> log/cron.log 2>> log/error.log'`

run the command with `bundle exec`:

`* * * * * /bin/bash -l -c 'cd /Users/app && /your-full-path/bundle exec script/rails runner -e development '\''Cron.get_categories'\'' >> log/cron.log 2>> log/error.log'`
 
... to find `your-full-path to bundle` just run `which` unix command, see my own here:
`$ which bundle
/home/lsoave/.rbenv/shims/bundle`
