### ISSUE TITLE
duplicated rules

### ISSUE THREAD

**Issue by introvert** [javan/whenever#547]
Hello,

I'm wondering why will whenever gem duplicate my scheduled / cron jobs?

When I open crontab -e I see 2 blocks:

    # Begin Whenever generated tasks for: /home/deployer/apps/..

and one for

     # Begin Whenever generated tasks for: my app name

The blocks contain the same cron jobs.

Why is that?

Thanks

**Comment by gucki** [comment]
I had the same problem, having rules getting appended with each deploy. So after X deploys I ended up with having the same entry X times in crontab!

The fix is simple, one has just to define the `application` or  `whenever_identifier` manually. So far example put `set :application, "my-awesome-app"` into your deploy.rb, clean your crontab once manually and then it should be working.

**Comment by benlangfeld** [comment]
This is [now explained in the README](https://github.com/javan/whenever/commit/65916c4deded492690c622c73856e382cdbfe402).

**Comment by sidcool1234** [comment]
I am already using this but not working for me.  Using Capistrano 2.

**Comment by benlangfeld** [comment]
Yes, you have to define one of those per the README @sidcool1234.
